### ISSUE TITLE
Unknown MemoryError

### ISSUE THREAD

**Issue by meongithub** [Digital-Sapphire/PyUpdater#45]
System info: Windows 10 64 bit

Installed PyUpdater with: `pip install PyUpdater[all]`

Tried to generate keys: `pyupdater keys -c`

Got this output in cmd:

`Are you sure you want to continue?`
`[N/y]?y`
`Please enter app name - No Default Available`
`--> drm`
`You entered drm, is this correct?`
`[N/y]?y`
`[ERROR]`

Relevant logged info:

[DEBUG] dsdev_utils.terminal 225: Under None
[DEBUG] dsdev_utils.terminal 232: Must be true
[DEBUG] pyupdater.utils 288: PyUpdater config data folder is missing
[DEBUG] pyupdater.utils 288: PyUpdater config data folder is missing
[DEBUG] dsdev_utils.terminal 225: Under None
[DEBUG] dsdev_utils.terminal 232: Must be true
[DEBUG] pyupdater.key_handler.keys 105: off_pri type: UGLplEMlkPgwJJqa2cghSVZoA+OKkV83iY5JZaCIyw8
[DEBUG] root 420: 
Traceback (most recent call last):
  File "c:\program files\anaconda3\lib\site-packages\pyupdater\cli\__init__.py", line 414, in main
    _real_main(args)
  File "c:\program files\anaconda3\lib\site-packages\pyupdater\cli\__init__.py", line 392, in _real_main
    keys(args)
  File "c:\program files\anaconda3\lib\site-packages\pyupdater\cli\__init__.py", line 181, in keys
    _keys(args)
  File "c:\program files\anaconda3\lib\site-packages\pyupdater\cli\__init__.py", line 204, in _keys
    k.make_keypack(app_name)
  File "c:\program files\anaconda3\lib\site-packages\pyupdater\key_handler\keys.py", line 69, in make_keypack
    keypack = self._gen_keypack(name)
  File "c:\program files\anaconda3\lib\site-packages\pyupdater\key_handler\keys.py", line 111, in _gen_keypack
    signing_key = ed25519.SigningKey(off_pri, encoding='base64')
  File "c:\program files\anaconda3\lib\site-packages\ed25519\keys.py", line 85, in __init__
    vk_s, sk_s = _ed25519.publickey(sk_s)
MemoryError

**Comment by JMSwag** [comment]
@meongithub I have not tested with anaconda. Do you get the same error with a standard python installation?

**Comment by meongithub** [comment]
@JMSwag Yes, I get the same error with python 3.5.2 (64-bit):

[DEBUG] dsdev_utils.terminal 225: Under None
[DEBUG] dsdev_utils.terminal 232: Must be true
[DEBUG] pyupdater.utils 288: PyUpdater config data folder is missing
[DEBUG] pyupdater.utils 288: PyUpdater config data folder is missing
[DEBUG] dsdev_utils.terminal 225: Under None
[DEBUG] dsdev_utils.terminal 232: Must be true
[DEBUG] pyupdater.key_handler.keys 105: off_pri type: yl4cwR19QfDMrzUaCJB1jiMkFumtJZ3Bp3Keef8SsI8
[DEBUG] root 420: 
Traceback (most recent call last):
  File "c:\users\meonpc\appdata\local\programs\python\python35\lib\site-packages\pyupdater\cli\__init__.py", line 414, in main
    _real_main(args)
  File "c:\users\meonpc\appdata\local\programs\python\python35\lib\site-packages\pyupdater\cli\__init__.py", line 392, in _real_main
    keys(args)
  File "c:\users\meonpc\appdata\local\programs\python\python35\lib\site-packages\pyupdater\cli\__init__.py", line 181, in keys
    _keys(args)
  File "c:\users\meonpc\appdata\local\programs\python\python35\lib\site-packages\pyupdater\cli\__init__.py", line 204, in _keys
    k.make_keypack(app_name)
  File "c:\users\meonpc\appdata\local\programs\python\python35\lib\site-packages\pyupdater\key_handler\keys.py", line 69, in make_keypack
    keypack = self._gen_keypack(name)
  File "c:\users\meonpc\appdata\local\programs\python\python35\lib\site-packages\pyupdater\key_handler\keys.py", line 111, in _gen_keypack
    signing_key = ed25519.SigningKey(off_pri, encoding='base64')
  File "c:\users\meonpc\appdata\local\programs\python\python35\lib\site-packages\ed25519\keys.py", line 85, in __init__
    vk_s, sk_s = _ed25519.publickey(sk_s)
MemoryError
[ERROR] root 421:

**Comment by meongithub** [comment]
I also found out that if I try to generate the  keys using the source code, the keys are generated just fine. How can I collect more information about on why the command line version fails?

**Comment by JMSwag** [comment]
Add a pyu.log to the root of the repo when you run the cli commands.

I'll try to reproduce with 64bit python.

**Comment by meongithub** [comment]
Content of pyu.log:

[DEBUG] dsdev_utils.terminal 225: Under None
[DEBUG] dsdev_utils.terminal 232: Must be true
[DEBUG] pyupdater.utils 288: PyUpdater config data folder is missing
[DEBUG] pyupdater.utils 288: PyUpdater config data folder is missing
[DEBUG] dsdev_utils.terminal 225: Under None
[DEBUG] dsdev_utils.terminal 232: Must be true
[DEBUG] pyupdater.key_handler.keys 105: off_pri type: yl4cwR19QfDMrzUaCJB1jiMkFumtJZ3Bp3Keef8SsI8
[DEBUG] root 420: 
Traceback (most recent call last):
  File "c:\users\meonpc\appdata\local\programs\python\python35\lib\site-packages\pyupdater\cli\__init__.py", line 414, in main
    _real_main(args)
  File "c:\users\meonpc\appdata\local\programs\python\python35\lib\site-packages\pyupdater\cli\__init__.py", line 392, in _real_main
    keys(args)
  File "c:\users\meonpc\appdata\local\programs\python\python35\lib\site-packages\pyupdater\cli\__init__.py", line 181, in keys
    _keys(args)
  File "c:\users\meonpc\appdata\local\programs\python\python35\lib\site-packages\pyupdater\cli\__init__.py", line 204, in _keys
    k.make_keypack(app_name)
  File "c:\users\meonpc\appdata\local\programs\python\python35\lib\site-packages\pyupdater\key_handler\keys.py", line 69, in make_keypack
    keypack = self._gen_keypack(name)
  File "c:\users\meonpc\appdata\local\programs\python\python35\lib\site-packages\pyupdater\key_handler\keys.py", line 111, in _gen_keypack
    signing_key = ed25519.SigningKey(off_pri, encoding='base64')
  File "c:\users\meonpc\appdata\local\programs\python\python35\lib\site-packages\ed25519\keys.py", line 85, in __init__
    vk_s, sk_s = _ed25519.publickey(sk_s)
MemoryError
[ERROR] root 421:

**Comment by JMSwag** [comment]
I'm able to reproduce. I'm also able to to generate the signing key just fine by hand. :weary:

This one may turn out to be interesting.

**Comment by JMSwag** [comment]
@meongithub This should be fixed in f1668d7c7f80455dff8fe08b3edaf89a5b4a9708

**Comment by marcelomanzo** [comment]
Issue still exists, both master and development

Python 3.6.2 (v3.6.2:5fd33b5, Jul  8 2017, 04:57:36) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
import 'atexit' # <class '_frozen_importlib.BuiltinImporter'>
>>>

C:\test2>pyupdater keys -c
106 INFO: PyUpdater 0+unknown
[INFO] PyUpdater 0+unknown
112 DEBUG: PyUpdater config data folder is missing
112 ERROR: Not a PyUpdater repo: You must initialize your repository first
[ERROR] Not a PyUpdater repo: You must initialize your repository first
Please enter app name - No Default Available
--> sdfas
12354 DEBUG: Under None
You entered sdfas, is this correct?
[N/y]?y
13674 DEBUG: Must be true
13674 ERROR:
[ERROR]
13690 DEBUG:
Traceback (most recent call last):
  File "c:\users\marce\appdata\local\programs\python\python36\lib\site-packages\pyupdater\key_handler\keys.py", line 99, in _gen_keypack
    app_pri, app_pub = self._make_keys()
  File "c:\users\marce\appdata\local\programs\python\python36\lib\site-packages\pyupdater\key_handler\keys.py", line 150, in _make_keys
    privkey, pubkey = ed25519.create_keypair()
  File "c:\users\marce\appdata\local\programs\python\python36\lib\site-packages\ed25519\keys.py", line 10, in create_keypair
    sk = SigningKey(seed)
  File "c:\users\marce\appdata\local\programs\python\python36\lib\site-packages\ed25519\keys.py", line 85, in __init__
    vk_s, sk_s = _ed25519.publickey(sk_s)
MemoryError
13690 ERROR: Failed to create keypair; please report this issue on https://github.com/JMSwag/PyUpdater/issues
[ERROR] Failed to create keypair; please report this issue on https://github.com/JMSwag/PyUpdater/issues
13690 ERROR: Failed to create keypack
[ERROR] Failed to create keypack

C:\test2>

**Comment by marcelomanzo** [comment]
is there an workaround to manually create the keys?

**Comment by marcelomanzo** [comment]
Issue Persists

pip install -U https://github.com/JMSwag/PyUpdater/tarball/master

Python 3.6.2 (v3.6.2:5fd33b5, Jul  8 2017, 04:57:36) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.

C:\Users\marce\repo\nextgendash>pyupdater keys -c
99 INFO: PyUpdater 0+unknown
[INFO] PyUpdater 0+unknown
99 DEBUG: PyUpdater config data folder is missing
99 ERROR: Not a PyUpdater repo: You must initialize your repository first
[ERROR] Not a PyUpdater repo: You must initialize your repository first
Please enter app name - No Default Available
--> SimRacingDash
5604 DEBUG: Under None
You entered SimRacingDash, is this correct?
[N/y]?y
8082 DEBUG: Must be true
8098 ERROR:
[ERROR]
8098 DEBUG:
Traceback (most recent call last):
  File "c:\users\marce\appdata\local\programs\python\python36\lib\site-packages\pyupdater\key_handler\keys.py", line 99, in _gen_keypack
    app_pri, app_pub = self._make_keys()
  File "c:\users\marce\appdata\local\programs\python\python36\lib\site-packages\pyupdater\key_handler\keys.py", line 150, in _make_keys
    privkey, pubkey = ed25519.create_keypair()
  File "c:\users\marce\appdata\local\programs\python\python36\lib\site-packages\ed25519\keys.py", line 10, in create_keypair
    sk = SigningKey(seed)
  File "c:\users\marce\appdata\local\programs\python\python36\lib\site-packages\ed25519\keys.py", line 85, in __init__
    vk_s, sk_s = _ed25519.publickey(sk_s)
MemoryError
8098 ERROR: Failed to create keypair; please report this issue on https://github.com/JMSwag/PyUpdater/issues
[ERROR] Failed to create keypair; please report this issue on https://github.com/JMSwag/PyUpdater/issues
8098 ERROR: Failed to create keypack
[ERROR] Failed to create keypack

C:\Users\marce\repo\nextgendash>

**Comment by JMSwag** [comment]
Please report to [python-ed25519](https://github.com/warner/python-ed25519). I get the same error when I execute ed25519 from the repl.

**Comment by marcelomanzo** [comment]
Is there any workaround that I could do?
I was able to use a linux machine to generate the keys.
It successful imported the keys in windows.

But when I try to sign the package I get....

C:\Users\marce\repo\nextgendash>pyupdater pkg -S
106 INFO: PyUpdater 0+unknown
[INFO] PyUpdater 0+unknown
112 DEBUG: Config Dir: C:\Users\marce\repo\nextgendash\.pyupdater
113 DEBUG: Config DB: C:\Users\marce\repo\nextgendash\.pyupdater\config.pyu
114 DEBUG: Config Dir: C:\Users\marce\repo\nextgendash\.pyupdater
115 DEBUG: Config DB: C:\Users\marce\repo\nextgendash\.pyupdater\config.pyu
116 DEBUG: Config Dir: C:\Users\marce\repo\nextgendash\.pyupdater
116 DEBUG: Config DB: C:\Users\marce\repo\nextgendash\.pyupdater\config.pyu
117 DEBUG: Config Dir: C:\Users\marce\repo\nextgendash\.pyupdater
117 DEBUG: Config DB: C:\Users\marce\repo\nextgendash\.pyupdater\config.pyu
118 DEBUG: Patch support enabled
158 DEBUG: found extension EntryPoint.parse('scp = scp_uploader:SCPUploader')
258 DEBUG: found extension EntryPoint.parse('s3 = s3_uploader:S3Uploader')
392 INFO: Signing packages...
[INFO] Signing packages...
394 DEBUG: Loading private key
394 DEBUG: Loading version data
395 DEBUG: Version file loaded

399 ERROR:
[ERROR]
401 DEBUG:
Traceback (most recent call last):
  File "c:\users\marce\appdata\local\programs\python\python36\lib\site-packages\pyupdater\cli\__init__.py", line 108, in main
    _real_main(args)
  File "c:\users\marce\appdata\local\programs\python\python36\lib\site-packages\pyupdater\cli\__init__.py", line 84, in _real_main
    dispatch_command(args, pyi_args)
  File "c:\users\marce\appdata\local\programs\python\python36\lib\site-packages\pyupdater\cli\__init__.py", line 97, in dispatch_command
    cmd(args, pyi_args)
  File "c:\users\marce\appdata\local\programs\python\python36\lib\site-packages\pyupdater\cli\commands.py", line 300, in _cmd_pkg
    pyu.sign_update()
  File "c:\users\marce\appdata\local\programs\python\python36\lib\site-packages\pyupdater\core.py", line 105, in sign_update
    self.kh.sign_update()
  File "c:\users\marce\appdata\local\programs\python\python36\lib\site-packages\pyupdater\key_handler\__init__.py", line 83, in sign_update
    self._add_sig()
  File "c:\users\marce\appdata\local\programs\python\python36\lib\site-packages\pyupdater\key_handler\__init__.py", line 125, in _add_sig
    encoding=self.key_encoding)
  File "c:\users\marce\appdata\local\programs\python\python36\lib\site-packages\ed25519\keys.py", line 85, in __init__
    vk_s, sk_s = _ed25519.publickey(sk_s)
MemoryError

**Comment by JMSwag** [comment]
@marcelomanzo I'm not aware of any at the moment.
